# Study_Numpy_Library
## Experiment - 8

### Gunjan Goyal
### 25070123048
### E&TC-A3

In [2]:
# Declaration of Numpy
import numpy as np

a = np.array([10,20,30,40])
b = np.array(([1,2,3],[4,5,6]))
print(a)
print(b)

[10 20 30 40]
[[1 2 3]
 [4 5 6]]


In [3]:
# Dimension of Array
print(a.ndim)
print(b.ndim)

1
2


In [11]:
# Shape
a.shape

(4,)

In [12]:
# Shape
b.shape

(2, 3)

In [15]:
# Data Type
a.dtype
b.dtype

dtype('int64')

#### In-Built Functions Using Numpy

In [17]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.arange(1,10,2)
# It gives numbers from 1-10 at a distance of 2

array([1, 3, 5, 7, 9])

In [27]:
np.linspace(0,1,5)
# 1 is not exclusive here
# 5 is the number of parts

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [28]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [30]:
print(b*2)
# b*2 is virtual
print(a+5)

[[ 2  4  6]
 [ 8 10 12]]
[15 25 35 45]


In [34]:
a + 5

array([15, 25, 35, 45])

In [35]:
b + 5

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [36]:
np.mean(a)

np.float64(25.0)

In [37]:
np.mean(b)

np.float64(3.5)

In [38]:
np.median(a)

np.float64(25.0)

In [39]:
np.median(b)

np.float64(3.5)

In [40]:
np.max(a)

np.int64(40)

In [41]:
np.max(b)

np.int64(6)

In [42]:
np.min(a)

np.int64(10)

In [43]:
np.min(b)

np.int64(1)

In [44]:
np.sum(a)

np.int64(100)

In [45]:
np.sum(b)

np.int64(21)